# https://python-poetry.org/docs/dependency-specification/
[tool.poetry]
name = "GamestonkTerminal"
version = "0.1.0"
description = ""
authors = ["Didier Rodrigues Lopes"]
packages = [
    { include = "gamestonk_terminal" },
]

[tool.poetry.scripts]
gst = 'terminal:terminal'

[tool.poetry.dependencies]
python = "^3.6.8"
pandas = "^1.1.5,<1.2"
iso8601 = "^0.1.14"
FundamentalAnalysis = "^0.2.6"
requests = "^2.25.1"
alpha-vantage = "^2.3.1"
finviz = "^1.3.4"
bs4 = "^0.0.1"
rapidfuzz = "^1.1.1"
yfinance = "^0.1.63"
pandas-ta = "^0.2.23b0"
prettytable = "^2.0.0"
psaw = "^0.0.12"
praw = "^7.1.4"
Quandl = "^3.6.0"
pytrends = "^4.7.3"
timeseries-cv = "0.1.4"
matplotlib = "^3.3.3"
plotly = "^4.14.3"
colorama = "^0.4.4"
papermill = "^2.3.2"
pmdarima = {version = "1.8.0", optional = false}
holidays = "^0.10"
prompt-toolkit = "^3.0.16"
jupyter = "^1.0.0"
mplfinance = "^0.12.7-alpha.7"
seaborn = "^0.11.0"
scipy = "~1.5.4"
fredapi = "^0.4.3"
screeninfo = "^0.6.7"
numpy = "~1.19.5,<1.20"
pyrsistent = "~0.14.11"
regex = "~2020.11.13"
h5py = "3.1"
robin-stocks = "^2.0.3"
termcolor = "^1.1.0"
alpaca-trade-api = "^1.0.1"
pyally = "^1.1.2"
pycoingecko = "^1.4.0"
detecta = "^0.0.5"
tradingview-ta = "^3.2.3"
finvizfinance = "^0.9.3"
Pillow = "^8.2.0"
statsmodels = "^0.12.2"
tabulate = "^0.8.9"
pyportfolioopt = "^1.4.1"
selenium = "^3.141.0"
python-coinmarketcap = "^0.2"
oandapyV20 = "^0.6.3"
valinvest = "^0.0.2"
bt = "^0.2.9"
python-binance = "^1.0.1"
grpcio = "1.34.0"
pyupgrade = "2.18.2"
cvxpy = "1.1.12"
tensorflow = {version = "2.5.0", optional = true}
jupyter-client = "6.1.12"
vaderSentiment = "3.3.2"
degiro-connector = "1.0.0"
mypy = "^0.901"
GitPython = "^3.1.17"
fear-greed-index = "^0.1.3"
pyEX = "^0.5.0"
charset-normalizer = "2.0.1"

[tool.poetry.dev-dependencies]
pytest = "^6.2.2"
pylint = "^2.7.2"
flake8 = "^3.9.0"
black = "21.5b2"
mypy = "^0.901"
mock = "^4.0.3"
codespell = "^2.0.0"
pyupgrade = "^2.11.0"
Sphinx = "4.1.1"

[tool.poetry.extras]
prediction = ["tensorflow", "pmdarima", "transformers", "flair", "torch"]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

# Notes for developers:
# 1. numpy >= 1.20.0 sometimes has issues with tensorflow=2.4.1
# 2. The following packages dropped support for python<3.7:
#    pandas >= 1.2.0
#    numpy >= 1.20.0
#    scipy >= 1.6.0
# 3. The following often cause poetry to misbehave:
#    pyrsistent >= 0.17
#    regex >= 2021
