name: Pull Request Labels
"on":
  pull_request:
    types: [opened, reopened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: minimum
          count: 1
          labels: "s-feature, m-feature, l-feature, build, refactor, tests, documentation, bug, enhancement"
      - uses: mheap/github-action-required-labels@v1
        with:
          mode: exactly
          count: 0
          labels: "do not merge"
