name: Windows 10 Full Clean Build with ML
env:
  PIP_DEFAULT_TIMEOUT: 100
  GTFF_USE_PROMPT_TOOLKIT: false
  GTFF_USE_ION: false
  GTFF_ENABLE_QUICK_EXIT: true
on:
  push:
    branches:
      - "main"
      - "full-builds"
  workflow_dispatch:
    inputs:
      comments:
        required: true
        description: 'Test scenario tags'
jobs:
  windows-conda:
    name: Windows-latest, Conda-latest,  Python 3.7
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Need to fetch more than the last commit so that setuptools-scm can
          # create the correct version string. If the number of commits since
          # the last release is greater than this, the version still be wrong.
          # Increase if necessary.
          fetch-depth: 100
          # The GitHub token is preserved by default but this job doesn't need
          # to be able to push to GitHub.
          persist-credentials: false

      - name: Setup caching for conda packages
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-windows-3-7-${{ hashFiles('requirements*.txt') }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: '3.7'
          miniconda-version: 'latest'
          auto-update-conda: true
          channels: conda-forge
          show-channel-urls: true
          environment-file: conda-environment.yaml
          activate-environment: testing
          # Needed for caching
          use-only-tar-bz2: true

      - name: Update Temp permissions on windows
        if: runner.os == 'Windows'
        shell: cmd /C CALL {0}
        run: >-
          c:\windows\system32\icacls C:\Users\runneradmin\AppData\Local\Temp /grant "everyone":F /t

      - name: Update pip version (Bash)
        shell: bash -l {0}
        run: |
          conda update pip
          pip --version
          pip cache dir

      - name: Get pip cache dir
        shell: bash -l {0}
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: pip cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: windows-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            windows-pip-

      - name: Install fbprophet with conda
        shell: bash -l {0}
        run: |
          conda install numpy=1.19.5
          conda install -c conda-forge fbprophet=0.6
          conda install spyder
          conda install gensim=3.8.3
          conda install -c conda-forge cvxpy=1.1.12

      - name: Install dependencies (Bash)
        shell: bash -l {0}
        run: |
          conda info
          pip install --user --requirement requirements-full.txt

      - name: List installed packages (Bash)
        shell: bash -l {0}
        run: |
          conda list
          pip list

      - name: Run tests (Bash)
        shell: bash -l {0}
        run: pytest tests/

      - name: Start Terminal and exit
        shell: bash -l {0}
        run: python terminal.py
